### ISSUE TITLE
Cannot remove custom domain

### ISSUE THREAD

**Issue by OKNoah** [isaacs/github#1213]
I configured a custom domain on my project and my `github.io` address redirects to it.

However, I now need to remove it and return to `github.io`, if possible.

How do I prevent github.io from redirecting?

**Comment by OKNoah** [comment]
@coliff I can't locate any CNAME in the repo. Pretty sure this was set in settings. Perhaps making a new CNAME of `ACCOUNT_NAME.github.io/REPO` would work? Although doing this didn't work in settings.

**Comment by coliff** [comment]
And make sure in the Settings the 'Custom domain' entry box is empty!

**Comment by OKNoah** [comment]
@coliff The box is empty, and when I click the drop down to select a branch for the Pages, the "none" option is disabled. I don't see another way to disable it. Sorry if I'm missing something obvious.

**Comment by coliff** [comment]
Strange..  If you have control over the domain name I guess you could set it to NOT point at GitHub then it'd be impossible for it to resolve. Can you tell us the domain name so we can take a look? Is the GitHub repo public?

**Comment by OKNoah** [comment]
@coliff The domain name expired and is currently being squatted by the domain name registrar (perhaps I can buy it back). Also the repo is oknoah/slipstream on the, and data in the www branch.

**Comment by coliff** [comment]
ugh, I'm running out of ideas... How about changing the repo name so the URL changes - maybe:
https://oknoah.github.io/slipstream_app or whatever.... worth trying.

**Comment by OKNoah** [comment]
No joy I’m afraid, simply forwards to myolddomain.com/sliptream_app

**Comment by coliff** [comment]
Ah! Your user page us: oknoah.github.io and there's a repo for that

I found this!
`https://github.com/OKNoah/oknoah.github.io/blob/master/CNAME` - is has the expired domain name in that.
Can you try removing that?

**Comment by OKNoah** [comment]
Wow, thanks so much for your help, would not have thought of that. Owe you one.

**Comment by davidmisiak** [comment]
I had the same problem and even when I removed everything that seemed to be connected to the Github Page, redirecting to incorrect website persisted. Turned out that it was due to Chrome cache - after deleting browsing data, the redirection vanished. I just thought it might help someone.

**Comment by mahdiASC** [comment]
`https://github.com/USERNAME/USERNAME.github.io/blob/master/CNAME`

I was lost without this!

Apparently your user's GitHub domain automatically comes from your `{username}.github.io` repo.
Come to find out the CNAME file there was doing the redirecting.

**Comment by KarelWintersky** [comment]
Same issue. 
Removed CNAME, cleared field `Custom domain`, but 
https://imaginariaru.github.io/RPGLinks/
redirecting to http://rpglinks.wintersky.me/

**Comment by coliff** [comment]
@KarelWintersky - the CNAME is still on your repo:
https://github.com/imaginariaru/rpglinks

Delete the CNAME and it'll stop redirecting.

**Comment by KarelWintersky** [comment]
@coliff 
What are you wrote at your DNS provider? 
A-records to github ips or CNAME to... what?

**Comment by coliff** [comment]
I use (and recommend) Cloudflare for this. A-records are pointing to GitHub.

**Comment by KarelWintersky** [comment]
@coliff 
A-records at your DNS provider and CNAME file in repo?

**Comment by coliff** [comment]
Yes

**Comment by KarelWintersky** [comment]
@coliff, thank you. I'll try/.

**Comment by lijon** [comment]
https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s

**Comment by mohmdalfaha** [comment]
No way !! I really got fed up with this stupid issue and even thought of migrating to Gitlab lmao 
It was only the Chrome cache issue 

Thanks !!

**Comment by coplayer** [comment]
I have same problem... T.T why not reset?
CNAME delete and rebuild

**Comment by frtug** [comment]
I have deleted the CNAME but it still redirects from the previous domain that I don't have

**Comment by justin226** [comment]
worked for me

**Comment by sivakon** [comment]
I have the same problem. CNAME was deleted. But still my domain https://kons.dev still redirects to Github
https://github.com/sivakon/sivakon.github.io/commit/cfbab2d26631b237e4ff39f67a4cfdde37489a20

**Comment by taufardh** [comment]
and now I face same problem... still redirecting to expired domain

**Comment by TPS** [comment]
Have any of y'all contacted GitHub support (support@github.com, ifF memory serves, or definitely the Support link at bottom of any GitHub page), pointing @ this issue, & then gotten any response?

**Comment by taufardh** [comment]
> Have any of y'all contacted GitHub support ([support@github.com](mailto:support@github.com), ifF memory serves, or definitely the Support link at bottom of any GitHub page), pointing @ this issue, & then gotten any response?

tbh.. I already solve my problem. there is a problem with cache in the browser, so the browser keeps redirect domain. but if cache cleared or open in incognito mode it's work fine. And there is a time delay from remove custom domain to become default github pages again.

**Comment by Rubix982** [comment]
Was facing the exact same issue! I had no CNAME file at my repo. Using the above suggestions, what worked for me was that I deleted my cache and it worked like magic.
Thanks, guys!

**Comment by Kaygi22** [comment]
Try to remove cache. I disabled cache and re-enabled it and it did the trick. 
f12 -> network tab -> disable cache
After that, refresh page, and voilà, the page works.

**Comment by hugocamelo** [comment]
if I delete a entire repo with CNAME and everything will it stop redirect too?

**Comment by amanmishra17** [comment]
> `https://github.com/USERNAME/USERNAME.github.io/blob/master/CNAME`
> 
> I was lost without this!
> 
> Apparently your user's GitHub domain automatically comes from your `{username}.github.io` repo.
> Come to find out the CNAME file there was doing the redirecting.

it worked for me I removed the CNAME and it worked. Thanks.

**Comment by Mondonno** [comment]
I try to disable github pages on my site but always:
![Zrzut ekranu 2020-10-1 o 15 33 11](https://user-images.githubusercontent.com/53169453/94815959-6d475c80-03fb-11eb-803f-d29919c74eca.png)
I do not know what to do, i privated my repo, so the github pages must disable but they not
Please help!

**Comment by Gibbo3771** [comment]
This is still busted.

I added my custom domain name with intention of using it, but then found out Cloudflare charge for resolving using page rules. Now I want to remove it and I just can't.

The custom domain box is **empty** and there is no **CNAME** file on _any_ of my branches.

**Comment by coliff** [comment]
@Gibbo3771 -it might take a little while for the DNS settings to propagate. Double-check the DNS settings in Cloudflare (make sure they aren't pointing to GitHub).

**Comment by Gibbo3771** [comment]
@coliff I never even got to adding it to Cloudflare. When I go to my pages link, it's redirecting me to my domain. So this is Githubs DNS that is either not propogating properly, or the setting is never removed.

**Comment by coderpranay** [comment]
@coliff 
I configured a custom domain on my project and my github.io address redirects to my custom domain.
Can you tell how i can remove?

**Comment by coliff** [comment]
@coderpranay delete the CNAME from the project if you don't want it there. if you need more help provide more details (maybe repo of your project)

**Comment by masoncooley** [comment]
I had to clear browser cache after I deleted the CNAME file for it to work.

**Comment by seahopki12** [comment]
Interesting. Same issue. I can view the page in incognito, but clearing cache doesn't not seem to do anything, nor does there appear to be any cache data to begin with.

https://github.com/seahopki12/React_Portfolio

**Comment by seahopki12** [comment]
^ I think I fixed my own issue.

Initially, I tried clearing my cache from the developer tools: 

F12 -> application -> storage -> check cache boxes -> clear site data.

This did not work for me.

Then, I tried the following method:

Chrome -> Clear browsing data... -> Select cached images and files -> clear data.

That did the trick for me.

**Comment by MrTyton** [comment]
Wait, is there a way if you have the {name}.github.io set up to not have a project be under that subdomain? I explicitly don't want that for one of my projects, I would much rather prefer the default github page.

**Comment by Triky313** [comment]
I emptied my cache and there is no CNAME either, but I still don't get the domain deleted. Does somebody has any idea?

https://github.com/Triky313/AlbionOnline-StatisticsAnalysis
