### ISSUE TITLE
Unicorn! - GitHub cannot load organization with lot of members

### ISSUE THREAD

**Issue by reebr** [isaacs/github#1623]
I think I found an interesting problem.

A curious thing happened when I tried to view the members of the [Epic Games][1] organization (_which currently has more than 221k members - just 2k of them are public users_).

<p align='center'><img src='https://user-images.githubusercontent.com/3982052/61084767-18d64c80-a405-11e9-9b9f-9bbbf1e7a1a5.png'></p>

The problem is that GitHub is unable to load members from organizations like this. When I try to access the [members page][2], it takes a very, very, very... time to be loaded. And when it's finally loaded, an error is displayed stating that the page took a long time to load (the famous 🦄  error)

<p align="center">
<img src="https://user-images.githubusercontent.com/3982052/61085018-a44fdd80-a405-11e9-91aa-99adb8b3a5b3.png">
</p>

### Steps to Reproduce
- You must be logged in.
- Just access the [/epicgames/people][2] page.
- Then, you will found your 🦄. 

[1]:https://github.com/EpicGames
[2]:https://github.com/orgs/EpicGames/people

**Comment by reebr** [comment]
Reported here: https://github.community/t5/How-to-use-Git-and-GitHub/Unicorn-I-can-t-see-the-members-of-a-specific-organization/m-p/26323#M7468

**Comment by clarkbw** [comment]
@reebr could you contact support with the link below the unicorn page? That'll get this going through the right channels.

**Comment by cirosantilli** [comment]
OMG I love unicorns. https://github.com/orgs/EpicGames/people only works if logged in.

**Comment by mobeigi** [comment]
@clarkbw I used the contact form to send support a message about this a while ago and was ghosted :D

**Comment by sudheersalavadi** [comment]
> OMG I love unicorns. https://github.com/orgs/EpicGames/people only works if logged in.

?

**Comment by mobeigi** [comment]
If your goal is to to 'publicize/conceal' your org status via that page. You can use these instructions provided by @Mattamorphic from the Github team:
https://github.community/t5/How-to-use-Git-and-GitHub/Unicorn-I-can-t-see-the-members-of-a-specific-organization/m-p/28893/highlight/true#M8117

**Comment by reebr** [comment]
@mobeigi thanks!

**Comment by reebr** [comment]
I received an email related to the open ticket.
The problem has been fixed. They find better ways to load members from organizations with many users.

**Comment by Chaitanyassr** [comment]
> I received an email related to the open ticket.
> The problem has been fixed. They find better ways to load members from organizations with many users.

problem is not fixed ..i m able to see the member page ...but not able to search.

**Comment by reebr** [comment]
So, the problem is not the same. =)
