### ISSUE TITLE
IPv6 support for Github Pages

### ISSUE THREAD

**Issue by stephengroat** [isaacs/github#354]
Are there any plans to implement IPv6 support for Github Pages? It's a great hosting solution (I'd even be willing to pay a few $ a year to keep having it), but the lack of IPv6 support is kinda a bummer.

**Comment by toreanderson** [comment]
This issue has been resolved:

```console
$ host toreanderson.github.io
toreanderson.github.io is an alias for sni.github.map.fastly.net.
sni.github.map.fastly.net has address 151.101.85.147
sni.github.map.fastly.net has IPv6 address 2a04:4e42:14::403
```
Cf. https://toreanderson.github.io/2017/07/30/update-ghp-fastly-ipv6.html

**Comment by kumy** [comment]
I can confirm too.

**Comment by vanaf** [comment]
Still missing AAAA records there https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

**Comment by tambry** [comment]
I'm afraid the issue is back. Someone has broken IPv6 support.

Example:
```
[root@me ~]# host ibm.github.io
ibm.github.io is an alias for sni.github.map.fastly.net.
sni.github.map.fastly.net has address 185.199.108.153
sni.github.map.fastly.net has address 185.199.109.153
sni.github.map.fastly.net has address 185.199.110.153
sni.github.map.fastly.net has address 185.199.111.153
```

**Comment by tekrobotics** [comment]
We were testing https security with the [SSL Server Test](https://www.ssllabs.com/ssltest/) and saw the same IPv4 addresses as above. IPv6 support seems to be broken at the moment. Using `host` returns the same confirmation.

**Comment by tambry** [comment]
GitHub's response:

> Thanks for writing in! The behavior you noticed is expected. This past week, we moved to an IPv4-only IP space to support HTTPS for GitHub Pages sites with custom domains:
> 
> https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
> 
> Support for IPv6 was an undocumented feature, and one that isn't supported by GitHub itself, but we removed IPv6 support on purpose over this last week.
> 
> Having said that, we can definitely see what you mean when it comes to providing support for IPv6. While I can't make any promises as to if or when we'll officially support it in the future, I'll let the team know you'd like to see us provide official support for IPv6.

**Comment by modonovan** [comment]
Hi team,
I'd love to resurrect this discussion (about re-enabling IPv6 on custom domains for GitHub pages sites. I'm a bit of a noob to GitHub if I'm totally honest and apart from doing the odd clone, add, commit, push from time to time I haven't really used the functionality that wisely. Recently though, I was at a meetup in Dublin where Anna Wilson (https://twitter.com/yesitsanna) was giving a talk. It was very much a seed change for me. I have been a hobbiest web developer over the years for the likes of clubs and societies and that kind of thing. Mostly hosted on either my own server using wordpress or similar. Anna's talk was extremely poignant in that it spoke of the real life challenges of doing this today and how it was high time to utilise something like GitHub pages to host your sites. The basic theory was that GitHub really knows where it's at in terms of "bug fixes", "security" and "best practice". With Jekyll integration in GitHub pages I've started to really agree. So much so that I recently migrated my test site (a personal blog) to GitHub pages. I migrated my DNS to point at it and all was seeming perfect until I started to notice some cert errors/notifications in Chrome. Ultimately it was due to the fact that the letsencrypt.org cert could not be attached to my site due to the presence of AAAA records in my DNS. 

I've since corrected that to remove them but I have to admit I feel it's a backward step. I was using letsencrypt on my own host and all was working with both IPv4 and IPv6. 

To that end I am seeking some support from the Github team to relaunch the availability of IPv6 (with https support) on GitHub pages.

Is there anyone in agreement with me on this?

Thanks in advance,

Mick

**Comment by tambry** [comment]
@modonovan Their old IPv6 CDN address still works – just add `2a04:4e42::403` to your domain.

**Comment by modonovan** [comment]
@tambry Cheers dude, is that an "official" way to get things working or does it "just work" using this address do you know?

**Comment by tambry** [comment]
@modonovan It just works, definitely not official. Quick correction to my previous comment – **it only works for non-HTTPS**. For HTTPS support GitHub uses their own IPv4 address space behind Fastly, and the old IPv6 addresses don't point to the newer infra, which is capable of serving HTTPS certificates for custom domains. But GitHub Pages itself still can serve using HTTPS over IPv6, it just returns `*.github.io` certificates. Should really only be a matter of GitHub adding their IPv6 address space to the CDN and documenting it ([they've already got their IPv6 prefixes since forever](https://bgp.he.net/AS36459#_prefixes6)).

[Their own custom load balancer](https://github.com/github/glb-director) supports IPv6 as far as I can tell, but that seems to be only used for everything besides their CDN endpoints and GitHub Pages.

FYI, one can reach GitHub's CDN domains (e.g. `assets-cdn.github.com`) through `[2a04:4e42::200:403]`, `[2a04:4e42::400:403]`, `[2a04:4e42::600:403]` (those should be Anycast addresses). Here are my hosts file entries for them:
```
2a04:4e42::400:403 assets-cdn.github.com
2a04:4e42::400:403 camo.githubusercontent.com
2a04:4e42::400:403 avatars0.githubusercontent.com
2a04:4e42::400:403 avatars1.githubusercontent.com
2a04:4e42::400:403 avatars2.githubusercontent.com
2a04:4e42::400:403 avatars3.githubusercontent.com
2a04:4e42::400:403 marketplace-images.githubusercontent.com
2a04:4e42::400:403 user-images.githubusercontent.com
2a04:4e42::400:403 raw.githubusercontent.com
```

**Comment by modonovan** [comment]
I see that's what I thought. Any chance we can lobby Github folks to maybe seek to make this officially supported and add the addresses behind Fastly inline with their IPv4 space?

**Comment by ydahhrk** [comment]
Is it just me or this problem is no longer exclusive to Github Pages?

```
me@Potato:~$ host -t AAAA github.com
github.com has no AAAA record
```

**Comment by arjenpdevries** [comment]
Not just you:
```
$ host -t AAAA github.com
github.com has no AAAA record
```

**Comment by vivienfr** [comment]
$ host -t AAAA github.com
github.com has no AAAA record

**Comment by Saiv46** [comment]
GitHub still not have IPv6 support, emailing them about that

**Comment by copperwiring** [comment]
Still no support :/

**Comment by drakontas** [comment]
Here's another vote for IPv6 support for GitHub Pages.  I'd like to make a site accessible to customers who are coming from IPv6-only connections.  Is there a timeline or this support that the team can share?

**Comment by MaciejKucia** [comment]
GitHub is not accessible in AWS egress-only internet gateway :(

**Comment by erkinalp** [comment]
> egress-only internet gateway

Do you read the words you have written? Egress means outwards.

**Comment by MaciejKucia** [comment]
Hello @erkinalp . Direction depends from which side is your perspective.
Please get familiar with https://docs.aws.amazon.com/vpc/latest/userguide/egress-only-internet-gateway.html

**Comment by Martin-Luther** [comment]
IPv6 People !!! What are you waiting for !??

**Comment by dR3b** [comment]
It is the year 2020! Welcome to the stone age!

**Comment by sgryphon** [comment]
Quite crazy. It is 2020, with this issue having been open for 5 years. About 30% of the Internet is now on IPv6, so quite a significant amount.

The HOSTS entries above for some of the sites (e.g. raw.githubcontent.com) work, because the underlying CDN now supports IPv6, so it should be simple (trivial) for GitHub to add that DNS entry for github.map.fastly.net 

The main site, github.com, does not use Fastly, but should also be pretty easy to add IPv6 to (or use the CDN to reverse proxy).

**Comment by miyurusankalpa** [comment]
> The main site, github.com, does not use Fastly, but should also be pretty easy to add IPv6 to (or use the CDN to reverse proxy).

Adding a reverse proxy to github.com maybe not as simple as it handles git traffic as well. However they already have a reverse proxy setup at AWS for the Asian countries and AWS have pretty good IPv6 support. https://www.whatsmydns.net/#A/github.com 

Github Engineering team seems to not care about IPv6. 

If they cared, they could have enable IPv6 for static content at fastly as you mentioned.
If they cared, they could have use dual stack s3 urls for github releases. 
If they cared, they could have give IPv6 address for github pages.  (it uses fastly with their own IPs)
If they cared, they could have enable IPv6 for github actions at azure.

**Comment by wenyuanyu** [comment]
It is 2021 now. +1 for the ipv6!

**Comment by Neustradamus** [comment]
To follow this missing feature ticket.

**Comment by jessuppi** [comment]
BTW if anyone is using GitHub Pages as a `mirrors` location for your servers to pull code from, you can `wget --inet4-only` or `curl --ipv4` in your scripts... this is what we are doing in SlickStack:

Bash functions: https://github.com/littlebizzy/slickstack/blob/master/bash/ss-functions.txt
GitHub Pages (mirrors): https://mirrors.slickstack.io/

**Comment by ingo-h** [comment]
it's surprising that such a professional and popular site still doesn't support ipv6 in 2021. I need it for my ipv6 only network. Please enable it.

**Comment by Neo-Desktop** [comment]
FYI just checked neither github.com nor github.io have AAAA records.

Not sure why this is acceptable at all

**Comment by Saiv46** [comment]
[Cloudflare Pages](https://pages.cloudflare.com/) supports IPv6, I think this can be used as alternative to Github Pages.

**Comment by miyurusankalpa** [comment]
According to [this tweet](https://twitter.com/faker_/status/1424789518578864139) Github has enabled IPv6 on some of their fastly resources. 

As they seem use the same IP format as IPv4, it is easy to deduct the IPv6 address for Github Pages.

```
185.199.108.153  - >  2606:50c0:8000::153
185.199.109.153  - >  2606:50c0:8001::153
185.199.110.153  - >  2606:50c0:8002::153
185.199.111.153  - >  2606:50c0:8003::153
```

I checked and SSL seems to work for the custom domains with IPv6 address. 🙌 (This was the issue for 2a04:4e42::133 IPs)

They have not updated the [documentation ](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) or added IPv6 to github.io domains.

**Comment by mathiashro** [comment]
Great news, thank you for sharing. Working here as well. Finally... are we going to close this issue?

**Comment by tkw1536** [comment]
Until the support for it becomes official (read: the documentation is updated to include it) I don't think this issue should be closed. 

See also [this HackerNews comment](https://news.ycombinator.com/item?id=28181943).

**Comment by TPS** [comment]
> They have not updated the [documentation](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) or added IPv6 to github.io domains.

I've added the `WIP` label for now, but don't think closing the issue is correct 'til it's completed.

**Comment by TPS** [comment]
Per https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/, this is now universally implemented.  Y'all confirm?
