### ISSUE TITLE
"Close & Comment" button should be "Comment and Close"

### ISSUE THREAD

**Issue by wallclockbuilder** [isaacs/github#461]

**Comment by wallclockbuilder** [comment]
You can find this button when you open a new issue and start typing a comment:
![comment-close-button](https://cloud.githubusercontent.com/assets/2033945/9677972/b322b5ca-52cf-11e5-94cd-e8fd0c233cb4.png)

**Comment by stuartpb** [comment]
Also, this should be colored like the "Close" button, not a neutral button.

**Comment by wallclockbuilder** [comment]
Good point. :+1:

**Comment by wallclockbuilder** [comment]
Maybe you can open an issue for that as well(don't forget to email github about it)

**Comment by stuartpb** [comment]
Actually, I'm pretty sure I did, at one point or another.

**Comment by stinos** [comment]
While at it, how about moving that button to e.g. the left side of the comment box? I'm pretty sure thousands of people already accidentally closed issues because of the color/location(right next to Comment)/order(before Comment)..

**Comment by wallclockbuilder** [comment]
You're right. I've seen a lot of colleagues accidentally close issues.

**Comment by tenorviol** [comment]
Having just accidentally "closed and commented", instead of "commented" for umpteenth time, I would like to suggest that this time saving feature be removed. There should be a "close" button, and a "comment" button. If you've written text into the comment box, the "close" button should become disabled. If the minority case comes up where one actually wants to comment AND close, submit the comment and then close the PR.

**Comment by spragchris** [comment]
This button should be red.

**Comment by yashbhavsar007** [comment]
> closed

**Comment by borromeotlhs** [comment]
Does anyone think that this issue could be made through a chrome extension?  

Thinking out loud as semantics bug me, too:
Perhaps the public source isn't needed if we can inject through the DOM for specific pages the css stylings we want over the UI buttons?  Or we could lift the functions out of any button, and then give JIT facelifts to entire pages?

**Comment by borromeotlhs** [comment]
Or what would be hella cool is a click and swipe for comment and close?  And it could be go from green (comment) to red (close) as you go from left to right for LTR languages, RTL or TTB (Chinese/Japanese)

**Comment by Marr11317** [comment]
If I am not mistaken, this one is now fixed

**Comment by markcmiller86** [comment]
FWIW, on GitHub

- I still see a button, `Close and Comment`
- I still get the close email *before* the comment email.

So, no, I don't think this is resolved.

**Comment by neil-m** [comment]
2020 and this issue still exists

**Comment by myroslavarm** [comment]
The "close and comment" button emphasises the "close" action first and foremost. I agree it's a bit confusing if you think about the grammar on its own, but next to the "comment" button, this particular order brings attention to the fact that you'll leave a comment _while_ closing the issue, which is a very important distinction.

As for the colour, neutral gray seems ok, as again your eye is attracted to the green in "comment", and you will only pay attention to the gray if you have set your mind on closing the issue.

Additionally, making the "close and comment" button just be a "close" button is totally bogus. People will start closing issues without any explanation, because no one will be bothered to write a comment, send it, and then separately close the issue. The way everything is structured now, the UI sort of inspires the user to explain issue closure, which is a big step in making the issue review process in particular and open source development in general more transparent & straightforward.

**Comment by erkinalp** [comment]
I would rather see Close&Comment event be completed in a single transaction and create single notification.

**Comment by markcmiller86** [comment]
Just for clarity...I actually like the *two* buttons...one that is just to add a comment and the other that plays the role of adding a comment *and* also closing the issue.

What is somewhat problematic though is

- Like @wallclockbuilder's initial comment...the correct logic flow is to **comment** and *then* **close**.
- Getting *two* notifications one with the comment and one saying the issue is closed. Like @erkinalp, I would prefer a *single* notification.
- Getting the close notification *ahead* of the *comment* notification (this happens often enough I don't think just an email delivery issue. I think they are actually emitted from GitHub in the wrong order). But, address second bullet and this issue goes away.

I think the argument that "the UI sort of inspires the user to explain issue closure" is actually not very strong even with the *sort of* qualifier. A UI that would have that effect though is a **Close** button (just the single word **Close**) that is grayed out (e.g. disabled) if the comment field is blank but that becomes enabled (perhaps with **Comment and Close**) once a comment is entered.

**Comment by markcmiller86** [comment]
👏 I am noticing on some repos I work in a new `Close with comment` button and, as well, that email notifications are ordered with comment coming first and then the close notification comming second. This addresses the first and third bullets in my comment [above](https://github.com/isaacs/github/issues/461#issuecomment-682089674). So, THANK YOU!

I still wouldn't complain if someone found a way to address bullet #2 and *merge* those two notifications into a single one.

**Comment by chetanyakan** [comment]
![image](https://user-images.githubusercontent.com/35728906/95235204-3c17c380-0823-11eb-9f4c-946dfc3fcee5.png)

**Comment by califa** [comment]
This is done :) 

<img width="304" alt="Screen Shot 2020-11-03 at 2 09 16 PM" src="https://user-images.githubusercontent.com/602352/98029939-44412f80-1dde-11eb-96ca-fd6422744f32.png">
