### ISSUE TITLE
Search by label using logical OR

### ISSUE THREAD

**Issue by superkhau** [isaacs/github#660]
I want to filter labels using a query like `label:bug OR label:feature`. Is there a way to do this? Seems to only support `AND` ATM.

**Comment by TPS** [comment]
Should probably implemented along with #65. :+1:

**Comment by davidschreiber** [comment]
This has been changed in the current GitHub version: By default labels now use OR. That's completely breaking my workflow – I consider this behavioral change a bug. Hope GitHub reverts that soon, or introduces another level of control.

**Comment by OliverJAsh** [comment]
> This has been changed in the current GitHub version: By default labels now use OR

I'm not seeing this. If I filter by two labels, the search performs an `AND`

**Comment by bltierney** [comment]
seems to be an 'AND' for both labels in a single issue. What I want is an OR across all issues.

**Comment by rue-dluria** [comment]
Having an option between 'OR' and 'AND' would be fantastic - a use case at my org is that many of our PRs have a "help wanted" or "ready for review" label, both of which mean that the PR needs attention, and there's no way to have a single filter that captures both.

**Comment by avalan4e57** [comment]
That would be quite helpful! It was a surprise for me when I've found out that there could be no optional logical  operators for search.

**Comment by jkassisbw** [comment]
hey. ho. lets go.

**Comment by anatoliyarkhipov** [comment]
Also it would be nice to have `OR` for search by authors

**Comment by tseabra** [comment]
For me its review :)
Suggestions: 
- review:none,changes_requested
- review:none|changes_requested
- review:none or review:changes_requested

**Comment by jotaen** [comment]
For me the use case is PRs. I’m looking for a search where I can see all PRs that I’m either author of, assigned to, or where someone requested my review. In brief, all PRs that I am somehow involved in, both per repo, as well as globally.

Syntax-wise I could imagine something along the lines of:

- `is:open is:pr ?assignee:USERNAME ?author:USERNAME ?review-requested:USERNAME`
- `is:open is:pr (assignee:USERNAME | author:USERNAME | review-requested:USERNAME)`

**Comment by alexfornuto** [comment]
+1

**Comment by OBreidenbach** [comment]
+1
An 'or' would be great. ;-)

**Comment by malyuk** [comment]
+1

**Comment by jotaen** [comment]
### Please refrain from answering with “+1” !

That generates a notification for all subscribers. Instead, you can add a thumbs-up reaction to the initial question to indicate your support.

**Comment by malyuk** [comment]
@jotaen - I am sorry about this. I was just over excited about possibility to use logical OR in issues filtering  and wanted to upvote :) 3 different teams are using shared repo for issue tracking on our end which creates a need for labeling that looks like this: 
![image](https://user-images.githubusercontent.com/1774051/33628966-68ca2ca8-d9d0-11e7-833a-9e463e694745.png)

Once I want to see all issues that are in QA, I have to go over each label and look at them individually. Ideally, I would like to sum them up.

**Comment by jtakalai** [comment]
Gitlab already does this (they seem to be using ElasticSearch). What gives? https://docs.gitlab.com/ee/user/search/advanced_search_syntax.html#using-the-advanced-syntax-search

**Comment by chris-heathwood-mood** [comment]
+1
Really slowing me down I have 4 filters I check on a regular basis which could be one if an 'or' existed.

**Comment by alexfornuto** [comment]
So I wonder how many others in this thread (myself included) didn't notice that this is not an official GitHub repo, only used for public tracking of issues otherwise sent privately.

That means for this feature request to get any love from GitHub, each of us should email support@github.com to voice our support for this idea.

See https://github.com/isaacs/github/blob/master/README.md for more details.

**Comment by pensiero** [comment]
+1

**Comment by artieshevchenko** [comment]
+1

**Comment by teknoraver** [comment]
If I try to find my commits on repo with more than 10 stars, I get a lot of results from repos with 0 star:

https://github.com/search?q=author:teknoraver+-user:teknoraver+stars:>10&type=Commits

what I'm doing wrong?

**Comment by TPS** [comment]
@teknoraver My guess? A typo & an unsafe encode.…  Try:
[https://github.com/search?q=author:teknoraver+-user:teknoraver+stars:%3E10+type=Commits](https://github.com/search?q=author:teknoraver+-user:teknoraver+stars:%3E10+type=Commits)

**Comment by teknoraver** [comment]
> @teknoraver My guess? A typo & an unsafe encode.… Try:
> https://github.com/search?q=author:teknoraver+-user:teknoraver+stars:%3E10+type=Commits

Hi. the `&type=Commits` is added automatically when switch from "repositories" and "commits" by clicking on the left menu

**Comment by CelerityAbbottPC** [comment]
Is this feature now implemented and ready for use?

**Comment by sypets** [comment]
There is also a StackOverflow question about this: [Can I search github labels with logical operator OR?](https://stackoverflow.com/questions/29136057/can-i-search-github-labels-with-logical-operator-or/53652481)

**Comment by oprogramador** [comment]
message from developer@githubsupport.com :

```
Hi Piotr,

Thanks for your feedback! We're always working to improve GitHub and we consider every suggestion we receive. I don't show that we are planning to offer logical OR in our searches this year, but I have added it to our internal Feature Request List.

We can't say if/when we may add a feature, however your feedback has definitely been recorded.

Cheers, 
GitHub Support
```

**Comment by alexfornuto** [comment]
heh, 3 years to get put on the list to maybe be looked at sometime after the next year.

**Comment by nikopen** [comment]
That's a copypasted response, did the same thing / had same response a while ago

**Comment by mantovani** [comment]
+1

**Comment by alanconway** [comment]
GMail has a full logical expression language, it's quirky - they use () groups to indicate AND and {} to indicate OR e.g  
    { (to:me label:foo) is:important }
in more traditional notation would be 
  (to:me AND label:foo) OR is:important

Either the gmail syntax (clearly google have a parser for it) or the more traditional syntax would be fine, but it's annoying to find a search engine that doesn't support basic logical operators, esp. on such an important resource.

**Comment by adrianoresende** [comment]
+1

`author:adrianoresende OR commenter:adrianoresende` don't work =/

**Comment by pressacco** [comment]
+1

**Comment by starryeyez024** [comment]
+1 three years for a simple OR operator? that's rough.

**Comment by hderms** [comment]
@starryeyez024 I agree I just googled to try to figure out if this is possible and I'm shocked to find that there's a three year old issue. Maybe more noise will get someones attention?

**Comment by alexfornuto** [comment]
@hderms et al: from the README of this repo:

> **This is not the actual repository for the GitHub website.**
>
>I'm not affiliated with GitHub in any way, except that I use it all day long, and almost all my code is hosted there.
>
>Issues and feature requests posted to GitHub are not stored in any publicly available location, so I find that I quickly lose track of the things that I've sent them.

**Comment by orcutt989** [comment]
+1 its nice when looking for issues with labels like "help wanted" OR "jump-in" when looking for a repo to contribute to.

**Comment by swandle06** [comment]
I added my +1 by sending an email to support@github.com.  I'll report back if I get anything informative in response.

**Comment by midlan** [comment]
I sent it them too, I've got response:

> Thanks for your feedback! We're always working to improve GitHub and we consider every suggestion we receive. I have added your request to be able to search using a logical OR as a +1 to our internal Feature Request List.
> 
> We can't say if/when we may add a feature, however your feedback has definitely been recorded.
> 
> Thanks,
> 
> Steve G.
> GitHub Support

**Comment by thrillyb** [comment]
There a way to +1 this other than an email? Please do this?

**Comment by michaellefkowitz** [comment]
More than two years later, adding my voice to all the others... come on GitHub, Boole did it in 1847, you can add this in 2019.

**Comment by sypets** [comment]
> Please don't write +1 comments, use the thumbs up :thumbsup: reaction instead.

> If you file an issue in this repository, be sure to also email support@github.com and include a link to the issue you have created. Also be sure to add as a comment to your issue any response(s) you receive from GitHub regarding your issue.

see [CONTRIBUTING.rst](https://github.com/isaacs/github/blob/master/CONTRIBUTING.md)

**Comment by marin-liovic** [comment]
this functionality is still missing? come on, this is very useful and probably easy to implement...

**Comment by gomo** [comment]
I hope to can specify priorities using `()` as below.

```
is:issue is:open (label:done OR label:ready) label:outsource
```

Or I think the following notation is also good.

```
is:issue is:open label:done,ready label:outsource
```

**Comment by JerryGreen** [comment]
@gomo what if I want something like:

```
mentions:JerryGreen OR author:JerryGreen
```

Unfortunately, it doesn't work.

**Comment by MartaD** [comment]
+1 for this feature, people need this!

**Comment by stangls** [comment]
We really miss this feature for a long time now.
I am thinking about moving some projects to a different issue-tracker.
Is there any possibility to have this soon on GitHub?

**Comment by alexfornuto** [comment]
I'll say it again, look where you are.

> @hderms et al: from the README of this repo:
> 
> > **This is not the actual repository for the GitHub website.**
> > I'm not affiliated with GitHub in any way, except that I use it all day long, and almost all my code is hosted there.
> > Issues and feature requests posted to GitHub are not stored in any publicly available location, so I find that I quickly lose track of the things that I've sent them.

**Comment by mfickett** [comment]
I sent an e-mail to support@github.com and got this autoreply:

> We now require that new support requests be created using our Support website:
> https://support.github.com/contact
> If you wouldn't mind re-submitting your message using that form, we'll be happy to help out however we can as soon as we have the opportunity.

I submitted a request via that site, and got an autoreply with Ticket ID 650367, then a human reply routing from dev support to product.

Also submitted a PR here to update the README to use the contact page instead of e-mail.

**Comment by TPS** [comment]
@mfickett Merged the (1st) PR, & thanks! 🙇🏾‍♂️

**Comment by ElectricRCAircraftGuy** [comment]
Related: 

1. https://stackoverflow.com/questions/29136057/can-i-search-github-labels-with-logical-operator-or/61618255#61618255 <-- here I describe the behavior I'd like to see.
1. Here is a shorter summary of the longer answer above: https://webapps.stackexchange.com/questions/57933/how-to-search-with-logic-operators-on-github/142071#142071

**Comment by Siedrix** [comment]
+1

**Comment by oprogramador** [comment]
> +1

@Siedrix could you like this issue (👍 or ❤️) and delete your `+1` comment?
In this way, we can easily compare issues by the number of 👍, ❤️ and 👎.

**Comment by Siedrix** [comment]
> > +1
> 
> @Siedrix could you like this issue (👍 or ❤️) and delete your `+1` comment?
> In this way, we can easily compare issues by the number of 👍, ❤️ and 👎.

Done

**Comment by shijinupc** [comment]
> +1
> 
> `author:adrianoresende OR commenter:adrianoresende` don't work but would be great to work

you may want to try https://docs.github.com/en/enterprise/2.19/user/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-a-user-thats-involved-in-an-issue-or-pull-request

**Comment by ruks** [comment]
+1 looks like this is a very important feature. But still not support :(

**Comment by stephancom** [comment]
my use case would be to find PR's I need to take action on:

```
is:pr is:open author:stephancom archived:false sort:updated-desc (-status:success OR review:changes_requested)
```

**Comment by chulman444** [comment]
https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-label

It says

> matches issues with the labels "bug" and "resolved."

But it's a logical AND? Either clarify this on the documentation or please implement this feature.

**Comment by anyayunli** [comment]
When will we have this? It's really helpful.

**Comment by alexfornuto** [comment]
Maybe now that GitHub has a [public roadmap](https://techcrunch.com/2020/07/28/github-starts-publishing-a-public-roadmap/) with a discussion feature, some brave soul can recreate this request there, and link back to this _private_ repo and its years of support for the idea.

**Comment by craigbrett17** [comment]
Another use case if it helps the discussion: We used to have teams mentioned in order to get their attention for PRs, but have recently moved to outright requesting their review. So seeing when there's a PR that someone in my team needs to pick up, I'd need a query like:

`is:open is:pr (team:MyOrg/Catstronaughts OR team-review-requested:MyOrg/Catstronaughts) archived:false`

**Comment by jeremythuff** [comment]
Yes please!

**Comment by stoooops** [comment]
Kind of sad this isn't supported by a 1.5 trillion dollar company.

**Comment by JamesTheAwesomeDude** [comment]
My use-case for this is: I'd like to be able to send users to the following query by default:  
[`is:open OR label:wouldfix`](https://github.com/JamesTheAwesomeDude/cerdicator/issues?q=is%3Aopen+OR+label%3Awouldfix)  
(except, have it actually _function_)

* many of the "issues" in my product are the _fault of_ an upstream vendor I intimately rely on but do not have leverage to get even _blockers_ fixed with
* I'd rather not clutter up the "Open" issues page with issues that I've mitigated to the best of my ability and squarely placed the remainder into upstream's domain
* I nevertheless would like users seeking help, following the "Support" link to find themselves at the above-described list so they don't think their crippling issue "somehow hasn't been reported" at first glance

**Comment by JerryGreen** [comment]
> I'd like to be able to send users to the following query by default

Interesting thought but I thought about other but similar feature:

**To be able to send MY TEAM to some custom query**

Currently it’s possible to simply use Projects, and fill up “to-do” with required issues. But turns out people don’t really use Projects, and use Issues page anyway. I find Issues page more convenient also, in overall. But it would be cool to be able to show other issues by default, rather than all open issues.

Btw, it’s not related here to the “logical OR” issue here. Maybe you want to create a new one? I would give it a like 👍

**Comment by JamesTheAwesomeDude** [comment]
> Btw, it’s not related here to the “logical OR” issue here. Maybe you want to create a new one?

Sorry—what?

Right now (as you can see), the link to the [attempted] logical-OR query is broken.

If logical-OR were implemented, the link would work as intended and I'd be free to variously distribute and embed it.

Thanks, however, for the mention of "Projects"; I'll look into that.

**Comment by a-elhag** [comment]
I can't believe that a simple issue as this can still not be fixed after four years. Other than sending an e-mail to Github, is there anything that we can do?

**Comment by nkoroste** [comment]
Any updates on this?

**Comment by nestor-custodio** [comment]
This is not only the most thumbed-up and most commented-on issue related to *search* specifically, but also the 7th most thumbed-up issue *overall*. It'll be hitting its 5-year milestone in just over 10 weeks.

HOW?? 🤦

**Comment by it-rec** [comment]
(label: Squad2 OR label: Squad1) AND (label: Release-2)

Something like this would be so great to search for!

**Comment by delfu** [comment]
> This is not only the most thumbed-up and most commented-on issue related to _search_ specifically, but also the 7th most thumbed-up issue _overall_. It'll be hitting its 5-year milestone in just over 10 weeks.
> 
> HOW?? 🤦

the feature request for follow organizations was from 2013 (785 👍 ) and is still pending 🤦

**Comment by mjonchhe** [comment]
Any updates on this yet? Any plans to allow logical OR  for search?

**Comment by bethanylang** [comment]
+1

**Comment by dpaks** [comment]
Any update on this? 5th anniversary is just about a month away!

**Comment by Rand-Random** [comment]
Happy 5th birthday!

**Comment by ahsf** [comment]
still open? come on ... 
this makes me want to switch back to CVS

**Comment by it-rec** [comment]
2021 - We can only search for `and`. Wo don't have a `or`-circut yet invented. We got to go to our collegues multiple decades back.

**Comment by Rocking80** [comment]
My God, 5 years passed and this issue is still OPEN!
What are those product owners of github?

**Comment by ElectricRCAircraftGuy** [comment]
FYI all: here's my answer, to provide insight meanwhile, on [Can I search github labels with logical operator OR?](https://stackoverflow.com/questions/29136057/can-i-search-github-labels-with-logical-operator-or/61618255#61618255)

**Comment by Levi-Lesches** [comment]
> And for anyone using GitHub for FREE, remember what you paid for it.

Honestly, this is a real head-scratcher in most support forums. I'd also love this feature, but for those of you losing your cool (not many), c'mon. It's a free service, and while new features and improvements are always nice, it's also free! Being appreciative of free software is one of the pinnacles of open-source.

**Comment by TPS** [comment]
@Levi-Lesches To be fair, if GitHub _was_ open-source, this would likely have been kludged in w/in a week of request, & _then_ (probably) properly added some point since then.

**Comment by oprogramador** [comment]
@superkhau 

Are you going to clone this proposal to https://github.com/github/feedback/discussions ?

**Comment by superkhau** [comment]
Wow, I can't believe this is still here! Let's hope this gets solved before the next half decade. 🍻

@oprogramador Unfortunately, I don't have admin rights and cannot convert this issue to a discussion.

**Comment by oprogramador** [comment]
@superkhau 

It seems that everybody can create a discussion there https://github.com/github/feedback/discussions/new but maybe you have to do that manually.

**Comment by superkhau** [comment]
@oprogramador Done! Please show your support at https://github.com/github/feedback/discussions/4507. 🚀

**Comment by Rand-Random** [comment]
@superkhau 
Forgot to close this? Or why keep both open?

**Comment by superkhau** [comment]
@Rand-Random I'm not sure if closing this will have any major ramifications -- what does everyone here think? 

Thumbs up this comment if you think this should be closed in favour of the linked discussion.

**Comment by 0xdevalias** [comment]
The official GitHub team and other maintainers are discussing the best way to handle migrations on another issue on this repo. I’d suggest not closing anything and letting them handle it all appropriately

**Comment by Levi-Lesches** [comment]
To be fair, closing an issue does nothing in terms of moving content. A bot can still read and move the comments and even a clossed issue can still be converted to a discussion (just tested to make sure). I think the issues here should be closed to indicate that future discussion should be done on the official forums and that this is here just for archival purposes.

What's likely to happen in terms of migration is that issues will be transferred to github/feedback and then converted to discussions there. Again, no impact if the issue is closed.

**Comment by 0xdevalias** [comment]
There may be no ‘technical limitation’, but by closing the issue it will likely fade into the noise of irrelevant/already fixed/duplicate/etc issues. It’s still an issue, thus it should stay open. At least until any official advice otherwise.

**Comment by michellemerrill** [comment]
👋🏼 hi everyone, closing this issue in favor of https://github.com/github/feedback/discussions/4507 - be sure to watch this space for updates on this enhancement soon!

**Comment by Rand-Random** [comment]
(test)

**Comment by TPS** [comment]
@michellemerrill Locked resolved doesn't seem _quite_ right yet… or does your update have _that_ quick an ETA? 🤔

**Comment by michellemerrill** [comment]
@TPS I agree -- I was locking it temporarily as we received some spam on it (which now looks to be deleted) -- unlocking, but keeping closed as we will comment on updates in the discussions thread. Stay tuned... soon!!!

**Comment by RanganaFernando** [comment]
If Google owns Github, they will definitely give this feature.
but you know Microsoft, they don't care

**Comment by emmaviolet** [comment]
@TPS it was a fairly quick ETA! https://github.blog/changelog/2021-08-02-search-issues-by-label-using-logical-or/

Do head to the feedback issue with any comments https://github.com/github/feedback/discussions/4507

**Comment by TPS** [comment]
@emmaviolet Just to find out, is that comma syntax usable w/ any _other_ filters, e.g., `user:`, `org:`, &c?

**Comment by emmaviolet** [comment]
> Just to find out, is that comma syntax usable w/ any other filters, e.g., user:, org:, &c?

@TPS sorry, I missed this! Currently this only works with issue labels. We could look into the others though :-)
