### ISSUE TITLE
Allow pull requests to be rebased from the UI

### ISSUE THREAD

**Issue by patcon** [isaacs/github#88]
Forked from #2:

@glasser

> Additionally, allowing you to rebase (or even rebase-and-squash) in the UI would be great, rather than needing to go into a local copy to do so. It would be perfectly fine if this only worked in non-conflicting cases.

**Comment by mar10** [comment]
:+1:

**Comment by mcshaman** [comment]
+1

**Comment by cvrebert** [comment]
So, GitHub [recently added an "Update branch" button](https://github.com/blog/2051-protected-branches-and-required-status-checks) to PRs, but it sounds like it adds another merge commit instead of rebasing :unamused:

**Comment by sparrc** [comment]
+1

**Comment by sparrc** [comment]
@tomek-brcm after `git merge --no-ff pr-branch` you can do a `git commit --amend` and add `Closes #NNN` to the commit message. That's what I do to close PRs from CLI

**Comment by SamHasler** [comment]
This is more needed for those that open pull requests as they are much less
likely to have the project checked out or know how to use the git cli to
rebase and squash commits.

**Comment by sarod** [comment]
:+1:

**Comment by tomek-brcm** [comment]
For me it boils down to the old Unix policy vs. mechanism design choice. Git is a great mechanism allowing us to choose a combination of merge, rebase, squash and fast-forward. It's also separate from the UI. The web UI mandates one, fixed policy, and policies tend to age very quickly.

It might be time to upgrade the policy to match current user requirements. Thanks to the separation between mechanism and policy it shouldn't be too difficult.

**Comment by jeznag** [comment]
This would be a great feature.

**Comment by gion** [comment]
I'm waiting for this feature for a while now :+1:

**Comment by jdom** [comment]
:+1:

**Comment by chumer** [comment]
:+1:

**Comment by woess** [comment]
:+1:

**Comment by gkalsi** [comment]
:+1:

**Comment by pnepywoda** [comment]
:+1:

**Comment by Jonty** [comment]
:+1:

**Comment by roc** [comment]
:+1:

**Comment by zaoral** [comment]
Really good feature.
It will be awsome only for update pr with master branch. Just to sync.
`git rebase repo/master`

**Comment by benblamey** [comment]
:+1:

**Comment by traversaro** [comment]
👍

**Comment by jplebre** [comment]
:+1:

**Comment by ket4yii** [comment]
Good feature. Yandex with their PR workflow suffers without it :smile: and use MergeQueue(their own tool) for autorebase and merging.

**Comment by jdom** [comment]
In case you didn't know (as it's tricky to see the option), this feature was already added on github. See https://github.com/blog/2141-squash-your-commits

**Comment by notriddle** [comment]
Could somebody please close this issue? It's been implemented.

**Comment by Jonty** [comment]
@jdom @notriddle AFAICS this is not implemented at all, that purely squashes commits on merge - it does not allow you to rebase a current branch against master without merging it.

**Comment by tomek-brcm** [comment]
Is it implemented somewhere? Where?

The feature jdom refers to is an equivalent of "git merge --squash". This issue is neither about merging nor about squashing. This issue is about a GUI equivalent of "git pull --rebase".

**Comment by jplebre** [comment]
what @Jonty and @tomek-brcm  said. The feature is to allow you to rebase a branch/pull request on the web's gui

**Comment by notriddle** [comment]
Ah, okay.

**Comment by ctartist621** [comment]
+1

**Comment by glasser** [comment]
https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by TPS** [comment]
@patcon @cirosantilli: As @glasser [mentioned above](https://github.com/isaacs/github/issues/88#issuecomment-249778087), this is solved now, right?

**Comment by jayunit100** [comment]
still would be nice to merge from the PR submission perspective

**Comment by pzrq** [comment]
<img width="688" alt="my thoughts are it s not fixed" src="https://cloud.githubusercontent.com/assets/1217010/20467181/c34ac668-afd5-11e6-80f2-1837255e840f.png">

 Squash and merge does work correctly, however a rebase would be really nice while the branch is still under review.

**Comment by jagthedrummer** [comment]
The "rebase and merge" option mentioned by @glasser is nice, but it would still be great to have just a "Rebase branch" button beside (or in place of) the "Update branch" button. One that _does not_ also merge the PR, just rebases it.

**Comment by galulex** [comment]
@jagthedrummer  [projectr](https://projectr.io/) allow you just to rebase you branch(PR) and also it has auto rebase feature that always keeps your opened PRs fresh.

**Comment by fpagnoux** [comment]
👍 

This is the kind of behaviour the current "Update Branch button" encourages 😢  : 
![image](https://cloud.githubusercontent.com/assets/11834997/23618542/e74c6608-0290-11e7-9831-8d9ceb81f695.png)

**Comment by tzaitsev** [comment]
How has this PR been open for nearly four years and there is no end in sight? It looks like manual rebasing for now or dare I say switching providers?

**Comment by ChristianCSE** [comment]
👍

**Comment by galulex** [comment]
Our history before using [ProjectR](https://projectr.io)
-

![before](https://cloud.githubusercontent.com/assets/483482/23933846/00fa77d8-094a-11e7-8fbf-87781a36d97e.png)
![before2](https://cloud.githubusercontent.com/assets/483482/23933848/02d223d0-094a-11e7-81cf-0e3f28f6b026.png)

After we connect [ProjectR](https://projectr.io) with autorebase feature turned on
-

![after](https://cloud.githubusercontent.com/assets/483482/23933843/fc7800cc-0949-11e7-85fe-0a46075a0a2d.png)

**Comment by maxim-rstor** [comment]
Any chance it's going to be supported one day? It looks like "Update branch" button still behaves as a merge, when the request was to have it as a rebase. That's actually pretty sad, we utilize the rebase strategy to have the master branch clean, and "merge" and "squash" are disabled for the master branch. But this button may break that easily as everyone still can click it and create a merge commit (commits) which we do want to avoid.

**Comment by bestekov** [comment]
ProjectR sounds cool, but I am mostly working with Github Enterprise where we cannot use public integrations. We desperately could use an "Update and Rebase" button instead of just "Update." Hopefully this isn't that hard given that it is fully supported through CLI? Though this Issue has been open for a long time, so perhaps there is more to the UI of this than expected?

**Comment by rsp** [comment]
:+1: **But...**

To anyone who wonders why this hasn't been implemented yet here are some potential problems that I see with that feature that may be the reason why it's not there yet - and possible solutions.

A pull request is made from some branch, possibly on a different repo, that may be private and not accessible to someone who has the right to merge it. In that case you cannot actually see the branch that was used in the PR, you cannot check it out and most definitely you cannot push to it - especially force push to it.

The author of the PR can always rebase the PR by making a local rebase and force pushing to the branch - this updates the PR and changes all of the commit hashes.

Now the question is if the Rebase PR button should:
1. **Force push to the PR author's branch as well** - it would have to force push to a branch that is possibly on a different repo which can be private and which the person who wants to click the Rebase PR button may have no access to.
2. **Leave the branch used in the PR alone and only rebase the actual PR** - something that would be visible when someone does `git fetch upstream pull/30/head:PR30` but not when the PR author does `git fetch origin feature-branch`, i.e. not affecting the branch of the PR author, only the PR itself.

In the **first case**, even if the person had access to that repo it is still a question question whether it is desirable to have a simple button that changes history of some other repo. Personally I would solve it with a 2-step process with a button called **Rebase Request** that someone who has merge rights clicks and the author of the PR confirms. Other people should see that a Rebase Request is in progress to know that the history might be changed. I think that a repo admin should be able to turn it off in the repo settings. It might even be good to turn it off by default but I see no reason why people who wants to use it shouldn't be able to. I just think that the PR author should be the one who actually rebases to avoid a situation where more work is in progress.

In the **second case**, this might lead to even more problems. It's not obvious what should happen on adding new commits to the branch used in the PR. Currently it updates the PR (and possibly invalidates the review) but it couldn't just add the same commit, it would need to automatically rebase it in the process and keep doing it for all new commits, or alternatively stop the PR from being updated when the PR author pushes new commits, which would be even more confusing.

Keep in mind that right now there are 3 ways to merge a PR, all of which have no problems like this. First of all the 3 ways to merge the PR close it in the process so there is no problem of pushing new commits - the PR is closed anyway. Also the Update Branch button which I hate personally has the advantage of adding a commit without changing the existing ones so it avoids the tricky problems that I described here.

But both **Squach and Merge** and **Rebase and Merge** have a more serious problem - they update the target branch before running the CI tests on the result. In my opinion they should work by creating a temporary branch with a merge, running the CI tests and other checks and only if everything passes fast-forwarding the real target branch to that temporary one.

I wonder what other people think. Personally I would prefer to have the temporary branch, or it may even be persistent and configurable of being the intermediate step between any PR and the protected target branch like master or develop but since this issue is about a Rebase button, I would prefer having a **Rebase Request** instead.

**Comment by samthebest** [comment]
To add to @rsp point, they probably haven't implemented this (and shouldn't) because it's simply not the correct way to use git.  Yes some people with low cognitive and command line capabilities don't like merge commits because they need a GUI to understand a history.  They are misunderstanding the point of history - to keep track of history!  Rebasing is tautologically a violation of basic software engineering principles - to preserve history, even if it's ugly.

Yes the world wars where terrible moments in history, and now we have huge history books documenting every detail.  Nevertheless they happened, events happened, at certain times, and for certain reasons - we should document and record those events exactly as they happened, in the order they happened, at the times they happened.

No we shouldn't allow 1000s of WIP commits into a master branch, but that's a total edge case that can be handled on the command line.  Why go to the hassle of implementing a feature for a few people who haven't figured out how git works yet, and a couple of rare edge cases that shouldn't be happening.

**Comment by michaelmior** [comment]
Some people who know how git works would still prefer to change history and avoid merge commits. I don't think you can make a blanket statement that everyone who does so is wrong. Since when is "preserve history, even if it's ugly" a basic software engineering principle? It's a reasonable choice for some people, but there seem to be many others who would prefer to make a different choice.

**Comment by samthebest** [comment]
@michaelmior  

> "preserve history, even if it's ugly" a basic software engineering principle?

No good design decision opts for deletion or compaction unless absolutely necessary given storage cost concerns.

Logging, append only database designs, edit history, this thread of communication, etc.

I suggest you delete your comment because it would make this thread easier to read and more aesthetically appealing.  Or perhaps we should change the order so all my comments appear next to each other? (would this thread make any logical sense if we did that?)

> but there seem to be many others who would prefer to make a different choice.

Those people haven't had a sufficiently wide depth of experience to understand the point being made.  Some day they will want to debug some pernicious issue, try to find leads in commit logs, only to find a highly aesthetically appealing yet useless rebased history.  They will say "ah, now I understand what those experienced developers where talking about, and why github doesn't implement rebase as an update option".

**Comment by Bessonov** [comment]
@samthebest your "arguments" like

> They will say "ah, now I understand what those [...]

are at a kindergarten niveau and doesn't make any contribution to the discussion.

**Comment by samthebest** [comment]
@Bessonov  I actually raise a point about debugging - a real issue that can cost companies millions. What does your ad hominem add?

**Comment by jeremyhaile** [comment]
👍

**Comment by tomek-brcm** [comment]
@samthebest I disagree. Github is a tool to be used, not a gospel to follow.

Different projects use different development methods, for example some prefer feature branches to isolate changes, others -  feature toggles. Some prefer to sort out merge conflicts in the merge commit to preserve the development history, others prefer rebase, some like linear history, some D-shaped merges after rebase, some regular merges without rebase.

Even git gui defaults to an incorrect but aesthetically pleasing view where commits on branches appear next to each other. You have to force the strict ordering if you really want to torture yourself with factually-correct but illegible mess of commits, branches and merges.

Can you describe an actual situation where a rebase caused severe debugging problem that would be trivial to find and fix otherwise?

**Comment by ZenGuLhe** [comment]
@samthebest > At best, you are some kind of Epic troll, in which case I have two things to say to you :

1. Congratulations on trolling, you did it well, you got me there I believed you.
1. Go do it somewhere else please. People are trying to work here, this amuses no one but you.

At worst you are missing one major point with your "people should know what has been done at what moment and in race condition with what other feature", is that accidental parallel development is just noise.
Knowing that "Alice" wrote the css while "Bob" was working on the html is purely irrelevant to anyone.
Moreover it should not, **ever**, be.

Saying : "We need to know what has been done in parallel to help debug it" is accepting that : "there will be bugs in our codebase due to the fact that people work in parallel".
Letting complexity leak to "_make up_" for the fact one did a sloppy work in the first place ...

**Comment by ZenGuLhe** [comment]
@samthebest > At best, you are some kind of Epic troll, in which case I have two things to say to you :

1. Congratulations on trolling, you did it well, you got me there I believed you.
1. Go do it somewhere else please. People are trying to work here, this amuses no one but you.

At worst you are missing one major point with your "people should know what has been done at what moment and in race condition with what other feature", is that accidental parallel development is just noise.
Knowing that "Alice" wrote the css while "Bob" was working on the html is purely irrelevant to anyone.
Moreover it should not, **ever**, be.

Saying : "We need to know what has been done in parallel to help debug it" is accepting that : "there will be bugs in our codebase due to the fact that people work in parallel".
Letting complexity leak to "_make up_" for the fact one did a sloppy work in the first place ...

Having a "merged all around" haystack is like having an omelette recipe look like :

```
*    Take out a pan
|\  
* |  Open the refrigerator
| *  Butter the pan
* |  Notice that you're out of eggs :/
| *  Heat the pan
* |  Go buy eggs
| *  Let your pan burn while you're out (buying eggs)
* |  Notice that you forgot your wallet
| *  The firemen are hosing ...
* |    Go back home
|\ \  
| |/  
| *  Notice that your flat's burned down :( (don't worry about the flat, it is described in a docker image, just start the container over)
* |    Answer Mom calling on your smartphone
|\ \  
| |/  
|/|   
| *  Ask cashier for a credit
* |  Ask mom if you can stay over
|/  
*    Bring eggs to mom's
|\  
| *  Chit chat with mom
* |  Cook
* |  Add herbs
|/  
*  Serve
```

There are so many irrelevant incidents there that should not have impact on the resulting omelette that you should not add those in the recipe.

**Comment by ZenGuLhe** [comment]
@samthebest > At best, you are some kind of Epic troll, in which case I have two things to say to you :

1. Congratulations on trolling, you did it well, you got me there I believed you.
1. Go do it somewhere else please. People are trying to work here, this amuses no one but you.

At worst you are missing one major point with your "people should know what has been done at what moment and in race condition with what other feature", is that accidental parallel development is just noise.
Knowing that "Alice" wrote the css while "Bob" was working on the html is purely irrelevant to anyone.
Moreover it should not, **ever**, be.

Saying : "We need to know what has been done in parallel to help debug it" is accepting that : "there will be bugs in our codebase due to the fact that people work in parallel".
Letting complexity leak to "_make up_" for the fact one did a sloppy work in the first place ...

Having a "merged all around" haystack is like having an omelette recipe look like :

```
*    Take out a pan
|\  
* |  Open the refrigerator
| *  Butter the pan
* |  Notice that you're out of eggs :/
| *  Heat the pan
* |  Go buy eggs
| *  Let your pan burn while you're out (buying eggs)
* |  Notice that you forgot your wallet
| *  The firemen are hosing ...
* |    Go back home
|\ \  
| |/  
| *  Notice that your flat's burned down :( (don't worry about the flat, it is described in a docker image, just start the container over)
* |    Answer Mom calling on your smartphone
|\ \  
| |/  
|/|   
| *  Ask cashier for a credit
* |  Ask mom if you can stay over
|/  
*    Bring eggs to mom's
|\  
* |  Cook
| *  Chit chat with mom
* |  Add herbs
|/  
*  Serve
```

There are so many irrelevant incidents there that should not have impact on the resulting omelette that you should not add those in the recipe.

**Comment by samthebest** [comment]
@ZenGuLhe 

> Knowing that "Alice" wrote the css while "Bob" was working on the html is purely irrelevant to anyone.

If it's the same file there are situations where that knowledge does provide information that can help debug pernicious issues, especially in highly stateful & available applications.  Knowing the topology of the branches and commits gives you information about the states of the brains of authors A' and B', and anyone knows that the "states of brains of authors" is critical in understanding bugs.

Your argument is just an "argument from lack of imagination".  The rebaser says "I cannot imagine a situation where this information is useful, therefore it's not useful, therefore I'll destroy it".

I can concede that such situations are an edge case, but will not concede they do not exist (from a posteriori experience and a priori hypothetical reasoning).  Finally the point you seem to fail to understand, is that nothing is lost by preserving information in an age where storage is cheap and history analysis tools are many.  One can always generate/simulate a rebased history from a merged history, but not visa versa - rebase is irreversible (technically using the combined reflogs of every local machine one might be able to recover a merged history from a rebased one, but not from the central repos reflog alone).

It is an **objective** fact that rebasing destroys history, it is only a _subjective_ belief that that history is not useful.

So there are three general programming principles here being lost on the rebaser:

 - Do not destroy data, store all of it
 - When raw data is complex, use tools to view it (I'm assuming you're using a browser to read this? not `curl`?)
 - Never perform an irreversible action if a reversible alternative exists

**Comment by michaelmior** [comment]
@samthebest I agree that there are situations where rebase is bad and destroying history is bad. But there are also situations where destroying history is good because the extra history just adds noise. What is lost by *not* rebasing can be an improvement in the signal to noise ratio when reviewing history.

I'm not saying this is always a good decision, but I don't see why the option to perform a rebase and the ability for each maintainer to make their own decision should be removed.

**Comment by samthebest** [comment]
@michaelmior  of course the feature should not be removed _from git_, but no need to implement it in _github_.  Come on, it takes github ages to release new UI features, let's not overload them now ;)

**Comment by samthebest** [comment]
@michaelmior  Yes history can be noisy, but we can remove that noise with tooling when we read the data.  Imagine if scientists started removing raw data because "it was noisy, so we only kept the bits we liked".  My point is a matter of principle/practice in any area that stores data - data should not be destroyed.  When data is complex, change the way you read it, not the data itself.

**Comment by ZenGuLhe** [comment]
@samthebest Yes, scientists remove raw datas, they do it every day.
They start with a ascertainment, formulate an hypothesis, then find a protocol to validate said hypothesis.
They are not gonna stop washing their hands before manipulating Petri dishes because it "would remove the raw data that they had had baloney for lunch".
(And, "for realsies", they do clean gotten data to get rid of noise or cast out contaminated samples in order to enhance p-value).

When you produce data (and commits or source files, ... are data) you don't record your keystrokes, you record what you want the file to look like in the end.

If you need to let bread crumbs like : "I wrote toString before hashCode, and both before equals, have fun with all my brain randomness when trying to figure out how to debug my pile of mess" your have way more serious problems than trying to make sure people will know why you thought backward (which you should have left as explicit comments if it's, god forbids, any relevant).

To use your fallacious way of, so "eloquently", putting things :

- It is an **objective** fact that noise is bad for signal transmission.
- It is a _subjective_ belief that loading history with myriads of brain-spew is enhancing later understandability of your code (like never removing any method but just commenting 'em out).

--
And just a side note regarding the "tooling assisted history clarifying". Name one tool that would figure out which commits are useful and which are garbage ?
My educated guess is : You can not. Because to do so, you would need to be able to determine, in advance, what is relevant and what is not (leading you to admit that, yes some commits are relevant and some are not).
But you can't do it because relevance is only measurable relatively to a purpose (which script do not, yet, possess). That purpose is yours to define and enforce.
Git's commit graph is not "history", the reality of when and how each commit was done is "history".
Git's commit graph is "a story", the one that you choose to tell, the one that your project need. The one that fits your purpose (which I hope you have because, if you don't, you are not developing, you are just "hacking and prayin'" which, I hope, you're not).

**Comment by samthebest** [comment]
@ZenGuLhe 

> They start with a ascertainment, formulate an hypothesis, then find a protocol to validate said hypothesis.

Use "an" before vowels and "a" before consonants. The statement may be true but is non sequitur to your argument.

> They are not gonna stop washing their hands before manipulating Petri dishes

This analogy is broken.  You avoid contamination, but when you **commit** to making a measurement you keep the raw measurements of the Petri dish. If by accident you include contaminated dishes you still publish the measurements of that contamination rather than alter the data as though the experiment was perfect. You can of course use tools (statistical, or visual, etc) to view the raw data in such a way that can reduce the impact of noise. For example removing outliers. Nevertheless it is critical in science to publish the raw data along with the cleaned data.  Suggest you watch this video https://www.youtube.com/watch?v=tgoWM4Jcl-s

Not publishing raw data will often mean your paper is not accepted, but publishing processed data and presenting it as raw data is very serious and can result in the academic being fired or even legal action (especially in medical trials).

Scientific data often has a lot of noise. We always keep a copy of the raw data with the noise so that it can be used by many peers to validate the statistical methods that remove that noise. Sometimes mistakes are made and it is this raw data where people will be able to understand the mistake.

Cleaned data can be tagged or versioned. The same applies to code - we can use git tags.

I can see from the rest of your post your brain does seem to have a "spew" problem, and I am having fun working out the "randomness". Nevertheless I'm an expert with a lot experience and so it's quite easy for me to debug your brain.

You are confusing measurements (commits) with process. We use processes (like TDD, using an IDE, rereading your own code, refactoring, etc) to improve the quality of code. We use commits to store the code permanently.

We don't commit every keystroke as the IDE (The process) helps us here. Similarly we don't measure the dish that fell on the floor.

In most companies the rule is that you should never commit code where not all the *unit* tests pass (though acceptance and integration tests can fail). Using this rule along with TDD means committed code gives a precise set of measurements together with their intention (the test).

P.S. don't write your own `hashCode` function in 2018, Use a modern language like Scala.

P.S.S I recommend you read "Thinking, fast and slow", it will help you understand your brain spew better https://www.amazon.co.uk/Thinking-Fast-Slow-Daniel-Kahneman/dp/0141033576

**Comment by aaccioly** [comment]
@samthebest. And then all of us newbies have been enlightened (http://stevelosh.com/blog/2013/04/git-koans/)... 

Meanwhile Bitbucket has implemented support for rebase flows: https://jira.atlassian.com/plugins/servlet/mobile#issue/BSERV-8252

Gerrit have a large rebase button since I can remember. Phabicator discards pre-merge history (final merge is a squashed commit).

I'm sick of arguing with "highly experienced experts" while my CI nightly builds are constantly broken due to a merge-based flow that can't guarantee that code changes are applied to and tested against the latest HEAD.

Nevermind rebasing and squashing. I can't even get something as simple as "--ff-only" approved because:

* "history should not be discarded"
* "something, something, git bisect / blame" and 
* "Yeah, we are going ahead and admitting that we are too lazy / slow to make sure that our changes have been applied to and tested agains't the latest HEAD. Let Git automatically merge it for us".

I've learned not to argue with Git (nor Haskell) experts. They are always right... Because "science".

To anyone trying to deal with a similar mess... There are better tools (and better jobs) around. Let the experts fend for themselves.

**Comment by samthebest** [comment]
> can't guarantee that code changes are applied to and tested against the latest HEAD.

@aaccioly  That is easy to fix, simply check the following setting in github

> Require branches to be up to date before merging
> This ensures the branch has been tested with the latest code on master.

**Comment by aaccioly** [comment]
@samthebest: If I'm not mistaken that comes enabled by default. The reason that it was disabled is probably the real reason why my decision to enable "-ff-only" was overriden. People don't want to manually rebase / merge to the latest head and wait for a green build... It's even worse to convince then when 9 out of 10 commits are automatic dependency updates (that yes, can also break the build).  A rebase button would certainly have a good psychological effect, and maybe - just maybe - solve my people problem (there is no such thing as technical problems, all problems are people problems).

**Comment by samthebest** [comment]
@aaccioly 

> People don't want to manually rebase / merge to the latest head 

Here is a script that will automatically merge master into your branch and push it.  Now that extra whole manual step that your devs seem incapable of doing will be easier.

```
#!/bin/bash
git pull origin master
git push origin $1
```

> and wait for a green build...

A build for merging into master ought to satisfy the "10 minute rule" i.e. be less than 10 minutes.  If your build so more than 10 mins your not really doing proper CI.

> all problems are people problems

That I completely agree with that, they say 99% of programmers can't code https://blog.codinghorror.com/why-cant-programmers-program/ .  1% is actually very optimistic after you throw in other skills like XP, KISS, Functional Programming, TDD.  After about 10 years in software development I've only met <5 devs who can even do both FP and TDD.

The problem is that the industry doesn't have a sufficiently large pay difference between *good* devs and *the rest*.  Yes these two devs make roughy 5x the norm, but they actually do easily 100x the work (factoring in the entire long term future of the product).  Good devs should be paid like good footballers.

This thread is case in point. It reminds me of https://en.wikipedia.org/wiki/Ignaz_Semmelweis who "invented" hand washing.  Doctors where actually offended when he told them they should wash their hands.  And here we have devs being offended when being told the basics of VCS, like merging instead of rebasing.

**Comment by aaccioly** [comment]
Hi @samthebest,

Build taking more than 10 minutes is a whole different drama that I
definitely wish I had the mussle to solve.

About bash scripts, git aliases, etc, nothing beats the psychological
effect of having a rebase / merge button that a dev / architect / "expert"
can click and be happy with (or maybe not since he still have to wait for
the build and there is always a small chance that something else will be
commited while he is waiting).

I appreciate your effort suggesting alternatives, but there's a reason for
me to write a rant in this specific issue.

My position stands: The rebase / merge button is a important feature for
Github Enterprise. There are complimentary (or even full replacement)
tools that already have such a button in place and they work fine (as in,
I  certainly had a better time keeping the build green with Gerrit and
would love to make it a standard tool across teams). Finally, yes, a
totally redundant big blue button in the UI would make my life so much
easier... Maybe even help mevenforce better Git policies.

I understand that there are other things going on ATM, however, as a user I
would like to cast my vote: Please implement a big blue rebase button even
if you feel that it's totally unnecessary and will certainly break
"something, something and git bisect". I'm ok with it. Actually, I'm more
than ok with it, this is currently the number one missing feature for me.
Pretty please?


On 18 Feb 2018 16:40, "samthebest" <notifications@github.com> wrote:

@aaccioly <https://github.com/aaccioly>

People don't want to manually rebase / merge to the latest head

Here is a script that will automatically merge master into your branch and
push it. Now that extra whole manual step that your devs seem incapable of
doing will be easier.

#!/bin/bash
git pull origin master
git push origin $1

and wait for a green build...

A build for merging into master ought to satisfy the "10 minute rule" i.e.
be less than 10 minutes. If your build so more than 10 mins your not really
doing proper CI.

all problems are people problems

That I completely agree with that, they say 99% of programmers can't code
https://blog.codinghorror.com/why-cant-programmers-program/ . 1% is
actually very optimistic after you throw in other skills like XP, KISS,
Functional Programming, TDD. After about 10 years in software development
I've only met <5 devs who can even do both FP and TDD.

The problem is that the industry doesn't have a sufficiently large pay
difference between *good* devs and *the rest*. Yes these two devs make
roughy 5x the norm, but they actually do easily 100x the work (factoring in
the entire long term future of the product). Good devs should be paid like
good footballers.

This thread is case in point. It reminds me of
https://en.wikipedia.org/wiki/Ignaz_Semmelweis who "invented" hand washing.
Doctors where actually offended when he told them they should wash their
hands. And here we have devs being offended when being told the basics of
VCS, like merging instead of rebasing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/isaacs/github/issues/88#issuecomment-366528568>, or mute
the thread

**Comment by repsejnworb** [comment]
@samthebest prior to merging our feature branches we want to ensure that all the commits in that branch will come in a group, and not spread out due to dates and when other people made their commits.

We know what we want for optimal control and understanding of changes in our master,
you do not.

Why should we have to resort to doing `git rebase origin/master && git push origin mybranch`, waiting for checkers (and hoping that nobody else merged in that time) and then merge?
You are wasting everyones time.
You disagree with a feature that will in no way be mandatory, nor change anything globally.

**Comment by samthebest** [comment]
@repsejnworb 

> Why should we have to resort to doing `git rebase origin/master && git push origin mybranch`, waiting for checkers (and hoping that nobody else merged in that time) and then merge?

All the button would do is save you from having to run `git rebase origin/master && git push origin mybranch`. You would still have to wait for tests and hope no one else merged while you tests are running (which shouldn't happen often unless your tests are slow).  If your team wants a clicky button just for a couple of commands in the terminal it's a worrying indication that your team is uncomfortable using the command line.

> You disagree with a feature that will in no way be mandatory, nor change anything globally.

Adding a feature isn't necessarily a good idea even if it's not mandatory.  Null pointers, the "Billion Dollar Mistake" is an example of a feature added to a language "because it was easy".  Consequently a lot of junior programmers who don't understand type systems, purity or side effects use Null and code bases become more buggy and difficult to maintain, consequently the industry has wasted billions of dollars.

The situation is the same here.  If the feature is added lots of junior programmers who don't understand git & version control will use the feature.  Consequently code bases will become more buggy and difficult maintain, consequently it will cost the industry a lot of money.

This thread is proof that lots of developers do indeed exist who do not even understand the basics of version control (merge instead of rebase).  Let's not give them rope.

**Comment by Donmclean** [comment]
It's been 15 years... I've created a Petition for this... https://chn.ge/2Hfr77R
Please sign so we can make this happen.

**Comment by zougloub** [comment]
Please, at least add a repo option to remove the suggestion to merge master into the PR branch and the associated button. This button is *evil*.

**Comment by samthebest** [comment]
@zougloub  So you want your tests to pass on the branch, but to fail when you merge to master? Hmm, sounds like you don't really understand the point of that button.

**Comment by dopplershift** [comment]
Or maybe, like me, they just don't want a whole bunch of extra merge commits cluttering up the git repository history. I'm fine with getting accurate CI results using that button. I am 100% not ok with those extra merge commits ending up in the final history.

**Comment by samthebest** [comment]
@dopplershift  If you have an issue with merge commits cluttering up history, you should use a different tool to browse history.  I tend to use `git log` plus `grep` and such and such, and I've never had any issues browsing history with merge commits.

It sounds like some weird OCD.

**Comment by dopplershift** [comment]
Glad that works for you. It doesn't for me.

Save your value judgements--I'm not asking you to do anything.

**Comment by jplebre** [comment]
@samthebest for a long time this thread has been been constantly hijacked by your condescending, patronising tone, often in a vain attempt of some misguided notion you *need* to desperately defend your workflow as an absolute way of working and a desperate *need* to educate all of us peasants on how we are "oh so wrong". It's been a one way conversation of people trying to introduce constructive criticism in the hopes to improve a feature, that is immediately rebuked by your cutting remarks (how do you have that much free time anyway?).

Your comments in this post have been detrimental to progress and improvement, at best, and toxic, at worst. 

Several people here have raised *concerns* that the feature is not implemented in a way to suit various workflows and can in some issues be harmful. I also tend to agree, and have seen this feature being misused. In a workflow with several hundred developers with slightly different workflows, being able to actually disable this would save hours and hours of headache.

Polite suggestion: there's hundreds of thousands of devs in this world earning their living doing what they do, and earning their business money (and in some cases, SERIOUS money). We are all different. You are not special in any way, just someone else with a different point of view. In London alone theres hundreds of on going meet ups with different Point of View, attended by several thousand of devs.

It is actually a relief to me that I'm one of the 99%:

> That I completely agree with that, they say 99% of programmers can't code https://blog.codinghorror.com/why-cant-programmers-program/ . 1% is actually very optimistic after 

Because if me and my colleagues lived in your definition of 99%, we'd all be miserable sods and we wouldn't be able to push companies from IPO to FTSE100 in a year. I'm glad people are no longer hiring classical CS graduates and trained engineers as software developers and are actually focusing on people, teams, and product instead.

I've had quite enough of this kind of elitist, competitive, toxic behaviour, and no matter how much I'd like to keep following this conversation I just can't.

Oh, and feel absolutely free to start picking on my grammar, link all your favourite blog posts, and wikipedia articles. Do tell me how I'm a complete idiot that is not good enough to be part of your 1%. Or how me and my team are doing our full time jobs wrong. You seem to have that sort of time to waste when it comes to talk down and shut down people whose views differ to yours. 
... Or bullying non-native english speakers.

**Comment by jplebre** [comment]
@zougloub cannot endorse your point enough. Many hours wasted since this became available as someone decided to "oh but it was there seemed like the right thing to press".
If a team/organisation has a specific workflow, being able to disable/enable the options would eliminate the possiblilty of pressing the wrong button for that given repo

**Comment by ulgens** [comment]
I'm writing from 2023, this feature is not implemented yet and nobody knows why.

**Comment by DBjelovuk** [comment]
Almost 6 years later. Has there even been an official response on this?

**Comment by rsp** [comment]
This is an update to [my comment above](https://github.com/isaacs/github/issues/88#issuecomment-300847473) (from May 2017)

Currently some CI services like Travis (but I don't think all of them) can be configured to run the tests **twice** - once on the PR branch itself and once on what would be the result of **merging** the PR to the base branch, so the problem that I described above can be mitigated somewhat if you use Travis and if you want to run the additional build (in practice I usually have to configure Travis to run the tests on both the original and the merged PR and not only on the merged PR because I need the tests on the actual branch anyway so it means running the build twice for every PR update which can sometimes take significant time).

**Comment by fkorotkov** [comment]
This feature can be added now via a [GitHub action](https://github.com/features/actions). Here are sources with instructions for the action: https://github.com/cirrus-actions/rebase. It will automatically rebase a PR on a `/rebase` comment.

![rebase-action](https://user-images.githubusercontent.com/989066/51547853-14a57b00-1e35-11e9-841d-33114f0f0bd5.gif)

**Comment by EwoutH** [comment]
@fkorotkov Looks very nice! But's insane there just aren't simple `Rebase` and `Rebase and Squash` buttons in the UI, especially at PR's.

**Comment by amsgames94** [comment]
👍

**Comment by danielloganking** [comment]
If I disable --no-ff merges for PRs on my repository (which I do) then it stands to reason that I would _not want_ the "Update Branch" button to add a merge commit. Can we at least get an administrative option that determines if the "Update Branch" button uses a `pull --rebase` or `merge` ? Especially considering that GitHubs own docs note that rebasing is an equally valid option: https://help.github.com/en/articles/about-required-status-checks

**Comment by tibdex** [comment]
The [Autorebase GitHub App](https://github.com/tibdex/autorebase) is similar to the previously mentioned GitHub Action but it can also be installed on public repos and it goes a bit further. Indeed, it doesn't stop to the one-time `/rebase` command, but rather makes the whole Rebase Workflow enjoyable.

**Comment by repsejnworb** [comment]
*cries in 2021 and the 'Update Button' still isn't configurable to rebase instead of merge*

**Comment by samthebest** [comment]
> _cries in 2021 and the 'Update Button' still isn't configurable to rebase instead of merge_

"cries" @repsejnworb ? Don't you mean celebration?  I think Github is doing a fantastic job of keeping this anti-pattern out of it's workflow.

Good on them from preventing the world from decending into a 1984 style dystopia, where force pushes are normal and history is what some developers want to see, rather than history being an accurate record of reality.

**Comment by samthebest** [comment]
@morficus Happy to help pal!  Here is the wikipedia definition:

> According to the authors of Design Patterns, there are two key elements to an anti-pattern that distinguish it from a bad habit, bad practice, or bad idea:
>
> 1. The anti-pattern is a commonly-used process, structure of pattern of action that, despite initially appearing to be an appropriate and effective response to a problem, has more bad consequences than good ones
> 2. Another solution to the problem the anti-pattern is attempting to address exists, and documented, repeatable and proven to be effective where the anti-pattern is not

So `rebase` satisfies both here because

1. People who use `rebase` (on pushed branches) _actually believe_ it to be an appropriate and effective response to a problem.  This thread is proof of that.  
2. Another solution, namely `merge` exists.  Not only is it documented it's even natively supported by Github as a button.

I guess the issue is that the users of the anti-pattern are not aware of the bad consequences of rebasing pushed branches, like it invoking `git push --force` and rewriting history via patch commutation.

The fundamental problem here is, developers often falsely identify themselves with their code.  So they perceive a `git branch` as a part of them, even after a branch is pushed.  Once a branch is pushed, the branch is now non-local it doesn't belong to anyone, it isn't part of anyones identity.  Therefore to rewrite that branch is to rewrite a distributed, accurate account of history.  Especially troublesome for _other developers_ who may also be working on that branch.

It's probably because some users find it hard to use `git` and read the `git` logs, because they are used to a GUI for viewing history.  They think it's better to rewrite history to be easier to consume, rather than change the tooling they use to consume it.

Although the consequences are unlikely as bad as Big Brother from 1984, the principle is the same - a record of history should not be altered for the convenience of a single party, no matter how complex the history, and no matter how inconvenient for the single party.

**Comment by danielloganking** [comment]
Rebasing a branch is not _inherently_ an anti-pattern. But even if it were, the button should still be configurable to allow repo owners to specify `--ff-only` merges which both satisfies a strict view about the evilness of `rebase` and accomplishes the desire of updating the branch the new head of the target without creating a merge commit. The fact that the "Update branch" button forces `--no-ff` simply makes it a footgun for for projects that are trying to maintain a linear history (for whatever reason).

**Comment by asbjornu** [comment]
@samthebest, ad hominem attacks on your opponents in order to portray them as less intelligent or less knowledgeable about Git than you only make you look bad and hurts your case.

Also, given your intense hate for `git rebase` and `git push --force`, I'm sure you're fighting just as hard, if not harder, for GitHub to remove support for [squash merge](https://docs.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests) and for Linus Torvalds to remove these features from Git altogether? I'm sure you have a pull request ready for Torvalds to review, removing these features already?

**Comment by morficus** [comment]
@samthebest you should read the git documentation about how `merge` differs from `rebase`. they are fundamentally different and can (and do) produce very different outcomes.

Instead of trying to quote a Wikipedia article about the Gang of Four, I invite you to explore the actual differences and valid use cases of using both `merge` and `rebase` as part of a workflow in place of sticking to some artificial restrictions you're choosing to impose.

**Comment by tomek-brcm** [comment]
@samthebest Nobody's forcing you to use rebase so why force everybody to avoid it? 

Secondly, there are genuine cases where the exact origin of the branch is of little importance. Most single-commit patches can easily be cherry-picked out of order. Git itself was modelled on Linux workflow. People were sending patches against the last released Linux version and maintainers applied those patches out of order on top of other, not yet released patches. It didn't kill Linux, did it? Remember the old "home taping is killing music" slogan? Your claim about the necessity of accurate history in git is equally false.

Git hub is a tool. It's supposed to make my work easier, not harder. I prefer the convenience of somewhat inaccurate history over pain of branch spaghetti "no matter how complex the history, and no matter how inconvenient". Yes, there are people who like pain, good for them. I don't so I started to avoid github. Simple.

**Comment by richardasmall** [comment]
its pretty disheartening to do a google search for something you thought would be so simple and see a thread that is now 8 years old that GitHub appears to be just completely ignoring.
